//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalProj
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.ReservedCars = new HashSet<ReservedCar>();
        }
    
        public string CarID { get; set; }
        public string Details { get; set; }
        public Nullable<int> KiloMetraz { get; set; }
        public bool IsOperational { get; set; }
        public short FactoryYear { get; set; }
        public string Branch { get; set; }
    
        public virtual CarDetail CarDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservedCar> ReservedCars { get; set; }
    }
}
